name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.13.1
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: mkdocs build
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site/**/*
